import type {
  Dossier,
  UploadedFile,
  Variable,
  Candidate,
} from "./types"

export const MOCK_DOSSIERS: Dossier[] = [
  {
    id: "1",
    name: "TargetCo",
    status: "Active",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    decision: "GO",
  },
  {
    id: "2",
    name: "TargetCo",
    status: "Earlier",
    createdAt: "2023-11-01T09:00:00Z",
    updatedAt: "2023-12-15T16:45:00Z",
    decision: "NO_GO",
  },
  {
    id: "3",
    name: "AcquireCo",
    status: "Archived",
    createdAt: "2023-09-10T08:00:00Z",
    updatedAt: "2023-10-20T11:00:00Z",
    decision: "GO",
  },
  {
    id: "4",
    name: "GrowthCo",
    status: "Archived",
    createdAt: "2023-07-01T09:00:00Z",
    updatedAt: "2023-08-15T14:00:00Z",
    decision: "NO_GO",
  },
  {
    id: "5",
    name: "ScaleCo",
    status: "Archived",
    createdAt: "2023-05-20T10:00:00Z",
    updatedAt: "2023-06-30T16:00:00Z",
    decision: "GO",
  },
]

export const MOCK_FILES: UploadedFile[] = [
  {
    id: "f1",
    dossierId: "1",
    name: "CIM.pdf",
    type: "pdf",
    status: "Ingested",
    size: 4500000,
    uploadedAt: "2024-01-15T10:05:00Z",
    createdAt: "2024-01-10T09:30:00Z",
  },
  {
    id: "f2",
    dossierId: "1",
    name: "Audited_Accounts.pdf",
    type: "pdf",
    status: "Ingested",
    size: 2800000,
    uploadedAt: "2024-01-15T10:10:00Z",
    createdAt: "2023-12-20T14:00:00Z",
  },
  {
    id: "f3",
    dossierId: "1",
    name: "Model.xlsx",
    type: "xlsx",
    status: "Ingested",
    size: 1200000,
    uploadedAt: "2024-01-15T10:15:00Z",
    createdAt: "2024-01-12T11:45:00Z",
  },
  {
    id: "f4",
    dossierId: "1",
    name: "Management_Deck.pptx",
    type: "pptx",
    status: "Ingested",
    size: 8500000,
    uploadedAt: "2024-01-15T10:20:00Z",
    createdAt: "2024-01-08T16:20:00Z",
  },
  {
    id: "f5",
    dossierId: "1",
    name: "DataRoom_QA.eml",
    type: "eml",
    status: "Ingested",
    size: 350000,
    uploadedAt: "2024-01-15T10:25:00Z",
    createdAt: "2024-01-14T08:15:00Z",
  },
]

export const MOCK_VARIABLES: Variable[] = [
  {
    id: "revenue-n1",
    name: "Revenue (Last Fiscal Year - N-1)",
    category: "financial",
    isCalculated: false,
    searchQueries: ["revenue last fiscal year", "turnover N-1", "net sales"],
    typicalLocations: ["Income Statement", "P&L", "Financial Summary"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "ebitda-n1",
    name: "EBITDA (Last Fiscal Year - N-1)",
    category: "financial",
    isCalculated: false,
    searchQueries: ["EBITDA last fiscal year", "operating EBITDA N-1"],
    typicalLocations: ["Income Statement", "P&L"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "top-customer",
    name: "Top Customer (% of Revenue)",
    category: "customer",
    isCalculated: false,
    searchQueries: ["top customer concentration", "largest customer"],
    typicalLocations: ["Customer Analysis", "Risk Section"],
    unitHints: ["%"],
  },
  {
    id: "gross-margin-n1",
    name: "Gross Margin (N-1)",
    category: "financial",
    isCalculated: true,
    searchQueries: ["gross margin", "gross profit margin"],
    typicalLocations: ["P&L", "Financial Summary"],
    unitHints: ["%"],
  },
  {
    id: "net-debt",
    name: "Net Debt",
    category: "capital",
    isCalculated: false,
    searchQueries: ["net debt", "net financial debt"],
    typicalLocations: ["Balance Sheet", "Debt Schedule"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "capex-n1",
    name: "CapEx (N-1)",
    category: "capital",
    isCalculated: false,
    searchQueries: ["capital expenditure", "capex"],
    typicalLocations: ["Cash Flow Statement", "Investments"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "employee-count",
    name: "Employee Count (FTE)",
    category: "market",
    isCalculated: false,
    searchQueries: ["employee count", "FTE", "headcount"],
    typicalLocations: ["HR Section", "Overview"],
    unitHints: ["FTE", "employees"],
  },
  {
    id: "revenue-n2",
    name: "Revenue (N-2)",
    category: "financial",
    isCalculated: false,
    searchQueries: ["revenue N-2", "prior year revenue"],
    typicalLocations: ["Income Statement", "P&L"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "ebitda-n2",
    name: "EBITDA (N-2)",
    category: "financial",
    isCalculated: false,
    searchQueries: ["EBITDA N-2", "prior year EBITDA"],
    typicalLocations: ["Income Statement", "P&L"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "revenue-growth",
    name: "Revenue Growth (YoY)",
    category: "financial",
    isCalculated: true,
    searchQueries: ["revenue growth", "YoY growth"],
    typicalLocations: ["Financial Summary", "KPIs"],
    unitHints: ["%"],
  },
  {
    id: "ebitda-margin",
    name: "EBITDA Margin",
    category: "financial",
    isCalculated: true,
    searchQueries: ["EBITDA margin", "operating margin"],
    typicalLocations: ["Financial Summary", "KPIs"],
    unitHints: ["%"],
  },
  {
    id: "working-capital",
    name: "Working Capital",
    category: "capital",
    isCalculated: false,
    searchQueries: ["working capital", "NWC"],
    typicalLocations: ["Balance Sheet", "Working Capital Analysis"],
    unitHints: ["EUR", "USD", "million"],
  },
  {
    id: "top-5-customers",
    name: "Top 5 Customers (% of Revenue)",
    category: "customer",
    isCalculated: false,
    searchQueries: ["top 5 customers", "customer concentration"],
    typicalLocations: ["Customer Analysis"],
    unitHints: ["%"],
  },
  {
    id: "market-size",
    name: "Target Addressable Market (TAM)",
    category: "market",
    isCalculated: false,
    searchQueries: ["TAM", "market size", "addressable market"],
    typicalLocations: ["Market Analysis", "Industry Overview"],
    unitHints: ["EUR", "USD", "billion"],
  },
  {
    id: "enterprise-value",
    name: "Enterprise Value",
    category: "deal",
    isCalculated: false,
    searchQueries: ["enterprise value", "EV"],
    typicalLocations: ["Valuation", "Deal Terms"],
    unitHints: ["EUR", "USD", "million"],
  },
]

export const MOCK_CANDIDATES: Candidate[] = [
  // Revenue N-1 - GREEN (consistent across sources)
  {
    id: "c1",
    dossierId: "1",
    variableId: "revenue-n1",
    value: 45200000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "12",
    snippet: "Revenue 45.2m",
    extractionConfidence: 0.95,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c2",
    dossierId: "1",
    variableId: "revenue-n1",
    value: 45200000,
    unit: "EUR",
    source: "Audited_Accounts.pdf",
    location: "8",
    snippet: "Total revenue EUR 45,200,000",
    extractionConfidence: 0.98,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c3",
    dossierId: "1",
    variableId: "revenue-n1",
    value: 45200000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "P&L!C12",
    snippet: "45,200",
    extractionConfidence: 0.92,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  // EBITDA N-1 - ORANGE (conflict)
  {
    id: "c4",
    dossierId: "1",
    variableId: "ebitda-n1",
    value: 8300000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "12",
    snippet: "EBITDA 8.3m",
    extractionConfidence: 0.88,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c5",
    dossierId: "1",
    variableId: "ebitda-n1",
    value: 7900000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "P&L!F22",
    snippet: "EBITDA 7.9m",
    extractionConfidence: 0.91,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  // Top Customer - RED (found in all, but inconsistent)
  {
    id: "c6",
    dossierId: "1",
    variableId: "top-customer",
    value: 18,
    unit: "%",
    source: "CIM.pdf",
    location: "24",
    snippet: "Largest customer represents 18%",
    extractionConfidence: 0.75,
    period: null,
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c7",
    dossierId: "1",
    variableId: "top-customer",
    value: 22,
    unit: "%",
    source: "Audited_Accounts.pdf",
    location: "15",
    snippet: "Top customer concentration: 22%",
    extractionConfidence: 0.82,
    period: null,
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c8",
    dossierId: "1",
    variableId: "top-customer",
    value: 19,
    unit: "%",
    source: "Model.xlsx",
    location: "Customers!B5",
    snippet: "19%",
    extractionConfidence: 0.70,
    period: null,
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c9",
    dossierId: "1",
    variableId: "top-customer",
    value: 20,
    unit: "%",
    source: "Management_Deck.pptx",
    location: "Slide 8",
    snippet: "Top customer: 20% of revenue",
    extractionConfidence: 0.85,
    period: null,
    extractedAt: "2024-01-15T11:00:00Z",
  },
  {
    id: "c10",
    dossierId: "1",
    variableId: "top-customer",
    value: 21,
    unit: "%",
    source: "DataRoom_QA.eml",
    location: "Body",
    snippet: "Our largest customer is ~21%",
    extractionConfidence: 0.65,
    period: null,
    extractedAt: "2024-01-15T11:00:00Z",
  },
  // Employee Count - GREEN
  {
    id: "c11",
    dossierId: "1",
    variableId: "employee-count",
    value: 245,
    unit: "FTE",
    source: "CIM.pdf",
    location: "5",
    snippet: "245 full-time employees",
    extractionConfidence: 0.95,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  // Net Debt for dossier 1
  {
    id: "c12",
    dossierId: "1",
    variableId: "net-debt",
    value: 12500000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "BS!D15",
    snippet: "Net debt 12.5m",
    extractionConfidence: 0.92,
    period: "N-1",
    extractedAt: "2024-01-15T11:00:00Z",
  },
  // ---- Dossier 2 (TargetCo Earlier) ----
  {
    id: "c20",
    dossierId: "2",
    variableId: "revenue-n1",
    value: 38000000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "10",
    snippet: "Revenue 38.0m",
    extractionConfidence: 0.94,
    period: "N-1",
    extractedAt: "2023-11-15T11:00:00Z",
  },
  {
    id: "c21",
    dossierId: "2",
    variableId: "ebitda-n1",
    value: 6200000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "10",
    snippet: "EBITDA 6.2m",
    extractionConfidence: 0.91,
    period: "N-1",
    extractedAt: "2023-11-15T11:00:00Z",
  },
  {
    id: "c22",
    dossierId: "2",
    variableId: "net-debt",
    value: 15000000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "BS!D15",
    snippet: "Net debt 15.0m",
    extractionConfidence: 0.89,
    period: "N-1",
    extractedAt: "2023-11-15T11:00:00Z",
  },
  // ---- Dossier 3 (AcquireCo) ----
  {
    id: "c30",
    dossierId: "3",
    variableId: "revenue-n1",
    value: 72000000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "8",
    snippet: "Revenue 72.0m",
    extractionConfidence: 0.96,
    period: "N-1",
    extractedAt: "2023-09-20T11:00:00Z",
  },
  {
    id: "c31",
    dossierId: "3",
    variableId: "ebitda-n1",
    value: 14400000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "8",
    snippet: "EBITDA 14.4m",
    extractionConfidence: 0.93,
    period: "N-1",
    extractedAt: "2023-09-20T11:00:00Z",
  },
  {
    id: "c32",
    dossierId: "3",
    variableId: "net-debt",
    value: 8000000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "BS!D10",
    snippet: "Net debt 8.0m",
    extractionConfidence: 0.90,
    period: "N-1",
    extractedAt: "2023-09-20T11:00:00Z",
  },
  {
    id: "c33",
    dossierId: "3",
    variableId: "employee-count",
    value: 380,
    unit: "FTE",
    source: "CIM.pdf",
    location: "5",
    snippet: "380 employees",
    extractionConfidence: 0.95,
    period: "N-1",
    extractedAt: "2023-09-20T11:00:00Z",
  },
  // ---- Dossier 4 (GrowthCo) ----
  {
    id: "c40",
    dossierId: "4",
    variableId: "revenue-n1",
    value: 28000000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "12",
    snippet: "Revenue 28.0m",
    extractionConfidence: 0.92,
    period: "N-1",
    extractedAt: "2023-07-15T11:00:00Z",
  },
  {
    id: "c41",
    dossierId: "4",
    variableId: "ebitda-n1",
    value: 4200000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "12",
    snippet: "EBITDA 4.2m",
    extractionConfidence: 0.88,
    period: "N-1",
    extractedAt: "2023-07-15T11:00:00Z",
  },
  {
    id: "c42",
    dossierId: "4",
    variableId: "net-debt",
    value: 22000000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "BS!D8",
    snippet: "Net debt 22.0m",
    extractionConfidence: 0.91,
    period: "N-1",
    extractedAt: "2023-07-15T11:00:00Z",
  },
  // ---- Dossier 5 (ScaleCo) ----
  {
    id: "c50",
    dossierId: "5",
    variableId: "revenue-n1",
    value: 95000000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "6",
    snippet: "Revenue 95.0m",
    extractionConfidence: 0.97,
    period: "N-1",
    extractedAt: "2023-05-25T11:00:00Z",
  },
  {
    id: "c51",
    dossierId: "5",
    variableId: "ebitda-n1",
    value: 19000000,
    unit: "EUR",
    source: "CIM.pdf",
    location: "6",
    snippet: "EBITDA 19.0m",
    extractionConfidence: 0.95,
    period: "N-1",
    extractedAt: "2023-05-25T11:00:00Z",
  },
  {
    id: "c52",
    dossierId: "5",
    variableId: "net-debt",
    value: 5000000,
    unit: "EUR",
    source: "Model.xlsx",
    location: "BS!D12",
    snippet: "Net debt 5.0m",
    extractionConfidence: 0.93,
    period: "N-1",
    extractedAt: "2023-05-25T11:00:00Z",
  },
  {
    id: "c53",
    dossierId: "5",
    variableId: "employee-count",
    value: 520,
    unit: "FTE",
    source: "CIM.pdf",
    location: "4",
    snippet: "520 full-time employees",
    extractionConfidence: 0.96,
    period: "N-1",
    extractedAt: "2023-05-25T11:00:00Z",
  },
]

// Helper to compute status from candidates
export function computeStatus(
  candidates: Candidate[]
): "GREEN" | "ORANGE" | "RED" {
  if (candidates.length === 0) return "RED"
  if (candidates.length === 1) {
    const c = candidates[0]
    if (c.extractionConfidence >= 0.7 && c.period) return "GREEN"
    return "ORANGE"
  }

  // Multiple candidates - check for value conflicts
  const values = candidates.map((c) =>
    typeof c.value === "number"
      ? (c.value / 1_000_000).toFixed(1)
      : c.value.toString()
  )
  const uniqueValues = [...new Set(values)]

  if (uniqueValues.length === 1) {
    // Same value across all sources = strong evidence
    return "GREEN"
  }

  // Different values = conflict
  return "ORANGE"
}

// Get coverage data for a variable across all files
export function getCoverageForVariable(
  variableId: string,
  files: UploadedFile[],
  candidates: Candidate[]
): Map<string, { status: "GREEN" | "ORANGE" | "RED"; candidates: Candidate[] }> {
  const coverage = new Map<
    string,
    { status: "GREEN" | "ORANGE" | "RED"; candidates: Candidate[] }
  >()

  for (const file of files) {
    const fileCandidates = candidates.filter(
      (c) => c.variableId === variableId && c.source === file.name
    )
    coverage.set(file.name, {
      status: fileCandidates.length > 0 ? computeStatus(fileCandidates) : "RED",
      candidates: fileCandidates,
    })
  }

  return coverage
}
