import { NextRequest, NextResponse } from "next/server"

// Simple PDF generator - creates a valid PDF document
function generatePDF(content: {
  dealName: string
  targetCompany: string
  variables: Array<{
    label: string
    value: string
    origin: string
    sourceDocument?: string
    justification?: string
    committeeDecision?: string
  }>
  generatedAt: string
  analyst: string
}): Uint8Array {
  // PDF structure
  const objects: string[] = []
  let objectCount = 0

  const addObject = (content: string): number => {
    objectCount++
    objects.push(`${objectCount} 0 obj\n${content}\nendobj\n`)
    return objectCount
  }

  // Catalog
  const catalogRef = addObject("<< /Type /Catalog /Pages 2 0 R >>")

  // Pages
  addObject("<< /Type /Pages /Kids [3 0 R] /Count 1 >>")

  // Build content stream
  let yPosition = 750
  const lineHeight = 14
  const contentLines: string[] = []

  // Helper to add text
  const addText = (text: string, x: number, y: number, fontSize = 10) => {
    // Escape special PDF characters
    const escaped = text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)")
    contentLines.push(`BT /F1 ${fontSize} Tf ${x} ${y} Td (${escaped}) Tj ET`)
  }

  // Title
  addText(`${content.dealName} - Screening Summary`, 50, yPosition, 16)
  yPosition -= 20
  addText(`${content.targetCompany}`, 50, yPosition, 10)
  yPosition -= 10
  addText(`Generated by ScreenR`, 50, yPosition, 8)
  yPosition -= 30

  // Horizontal line
  contentLines.push(`50 ${yPosition} m 550 ${yPosition} l S`)
  yPosition -= 20

  // Variables header
  addText("Variable", 50, yPosition, 9)
  addText("Value", 180, yPosition, 9)
  addText("Source", 290, yPosition, 9)
  addText("Decision", 420, yPosition, 9)
  yPosition -= 5
  contentLines.push(`50 ${yPosition} m 550 ${yPosition} l S`)
  yPosition -= lineHeight

  // Variables
  for (const v of content.variables) {
    if (yPosition < 120) break // Stop if we run out of page space

    addText(v.label.substring(0, 22), 50, yPosition, 8)
    addText(v.value.substring(0, 18), 180, yPosition, 8)
    addText((v.sourceDocument || v.origin).substring(0, 20), 290, yPosition, 8)
    addText(v.committeeDecision || "-", 420, yPosition, 8)
    yPosition -= lineHeight

    // Add justification line if present
    if (v.justification) {
      addText(`Rationale: ${v.justification.substring(0, 70)}`, 60, yPosition, 7)
      yPosition -= lineHeight
    }
  }

  // Footer
  yPosition = 50
  contentLines.push(`50 ${yPosition + 10} m 550 ${yPosition + 10} l S`)
  addText(`Generated: ${content.generatedAt}`, 50, yPosition, 8)
  addText(`Analyst: ${content.analyst}`, 300, yPosition, 8)
  addText(`ScreenR`, 500, yPosition, 8)

  const contentStream = contentLines.join("\n")

  // Content stream object
  const streamRef = addObject(
    `<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream`
  )

  // Page
  objects[2] = `3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${streamRef} 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n`

  // Font
  addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

  // Build PDF
  let pdf = "%PDF-1.4\n"
  const xrefOffsets: number[] = []

  for (const obj of objects) {
    xrefOffsets.push(pdf.length)
    pdf += obj
  }

  const xrefStart = pdf.length
  pdf += "xref\n"
  pdf += `0 ${objectCount + 1}\n`
  pdf += "0000000000 65535 f \n"
  for (const offset of xrefOffsets) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`
  }

  pdf += "trailer\n"
  pdf += `<< /Size ${objectCount + 1} /Root ${catalogRef} 0 R >>\n`
  pdf += "startxref\n"
  pdf += `${xrefStart}\n`
  pdf += "%%EOF"

  return new TextEncoder().encode(pdf)
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ dealId: string }> }
) {
  const { dealId } = await params

  try {
    const body = await request.json()
    const { dealName, targetCompany, variables, analyst } = body

    const pdfBytes = generatePDF({
      dealName: dealName || `Deal ${dealId}`,
      targetCompany: targetCompany || "Target Company",
      variables: variables || [],
      generatedAt: new Date().toLocaleDateString(),
      analyst: analyst || "Analyst",
    })

    const fileName = `ScreenR_${dealId}_${new Date().toISOString().split("T")[0]}.pdf`

    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "Content-Length": pdfBytes.length.toString(),
      },
    })
  } catch (error) {
    console.error("PDF generation error:", error)
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 })
  }
}
